// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Nishanth Samala
// Export every hand-authored annotation in a program to a portable JSON file.
//
// WHY. Annotations live in the Ghidra program database, not in the binary, so anything that
// forces a re-import loses them: a SLEIGH language-VERSION bump is the common one. Ghidra
// stamps the installed language version into every program it saves and then refuses to
// reopen that program against an older language --
//
//     Failed to open program: Language version (V0.2 or later) required for '<lang>'
//
// -- so moving to a branch whose .ldefs declares a lower version locks the program out
// entirely. There is no downgrade path; the fix is to re-import the raw image, re-run the
// setup/seed pipeline, and re-apply the annotations. This script is the "save" half of that,
// and ImportAnnotations.java is the "restore" half. Export BEFORE changing the installed
// language, while the programs still open.
//
// It is also the general answer to hand-maintained re-apply scripts: instead of transcribing
// renames into Java by hand, export them.
//
// WHAT IT CAPTURES. Function names, prototypes, calling conventions, no-return flags, tags,
// and non-default parameter/local names+types; non-default labels; named data and its type;
// every comment (plate / pre / EOL / post / repeatable) at any address; and user bookmarks.
//
// DATA TYPES. The JSON only LISTS user-defined types -- serializing a struct layout by hand
// would be a worse version of a format Ghidra already has. Pass "gdt" to write a real .gdt
// archive next to the JSON instead: that captures every type in the program's manager, layout
// and all, and ImportAnnotations resolves against it once you have opened it in the target.
// Without "gdt" the type NAMES in the JSON only reapply if the target already knows them.
//
// WHAT IT DOES NOT CAPTURE. Analysis-created labels and Error/Warning bookmarks are skipped on
// purpose: they are regenerated by re-running the pipeline.
//
// ADDRESSES are written as Ghidra address strings, not as numbers, so the file round-trips
// through getAddressFactory().getAddress() on any language -- including word-addressed ones
// like C28x where a code unit is 2 bytes and Address.getOffset() is a BYTE offset.
//
// USAGE.
//   ExportAnnotations <outDir>
//       export the CURRENT program.
//   ExportAnnotations <outDir> batch [languageFilter]
//       export EVERY program in the project, opening and releasing each in turn.
//       languageFilter is a substring match on the language ID -- pass e.g. "TMS320C28x"
//       to skip unrelated programs. Already-open programs are exported without being
//       closed; the rest are released afterwards.
//   Add "gdt" anywhere in the arguments to also write a .gdt data-type archive per program.
// With no outDir it writes to <user.home>/ghidra_annotations/. Output files are named
// after the program's PROJECT PATH, not just its name, so two programs that share a name
// in different folders cannot overwrite each other.
// Keep the output somewhere private if the program is one you cannot publish.
//
// @category Annotations
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

public class ExportAnnotations extends GhidraScript {

    private boolean writeGdt;

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String outDir = args.length > 0 && !args[0].isBlank()
            ? args[0]
            : System.getProperty("user.home") + File.separator + "ghidra_annotations";
        Files.createDirectories(Paths.get(outDir));

        for (String a : args) if ("gdt".equalsIgnoreCase(a)) writeGdt = true;
        boolean batch = args.length > 1 && "batch".equalsIgnoreCase(args[1]);
        if (!batch) { exportProgram(currentProgram, outDir); return; }

        String langFilter = args.length > 2 ? args[2] : null;
        List<ghidra.framework.model.DomainFile> files = new ArrayList<>();
        collect(state.getProject().getProjectData().getRootFolder(), files);
        println("batch: " + files.size() + " file(s) in project"
            + (langFilter == null ? "" : ", filtering language ~ " + langFilter));
        int done = 0, skipped = 0, failed = 0;
        for (ghidra.framework.model.DomainFile df : files) {
            if (monitor.isCancelled()) break;
            Map<String,String> md = df.getMetadata();
            String lang = md == null ? null : md.get("Language ID");
            if (langFilter != null && (lang == null || !lang.contains(langFilter))) { skipped++; continue; }
            if (!Program.class.isAssignableFrom(df.getDomainObjectClass())) { skipped++; continue; }
            Program p = null;
            boolean opened = false;
            try {
                p = (Program) df.getOpenedDomainObject(this);
                if (p == null) { p = (Program) df.getDomainObject(this, false, false, monitor); opened = true; }
                exportProgram(p, outDir);
                done++;
            } catch (Exception e) {
                println("  ! " + df.getPathname() + ": " + e);
                failed++;
            } finally {
                // Release only what this script opened -- releasing a program the user has
                // open in a tool would close it out from under them.
                if (p != null && opened) p.release(this);
            }
        }
        println(String.format("batch done: exported %d, skipped %d, failed %d", done, skipped, failed));
    }

    private void collect(ghidra.framework.model.DomainFolder f,
                         List<ghidra.framework.model.DomainFile> out) {
        for (ghidra.framework.model.DomainFile df : f.getFiles()) out.add(df);
        for (ghidra.framework.model.DomainFolder sub : f.getFolders()) collect(sub, out);
    }

    private void exportProgram(Program currentProgram, String outDir) throws Exception {
        JsonObject root = new JsonObject();
        root.addProperty("schema", 1);
        root.add("program", programHeader(currentProgram));

        JsonArray functions = new JsonArray();
        JsonArray labels = new JsonArray();
        JsonArray data = new JsonArray();
        JsonArray comments = new JsonArray();
        JsonArray bookmarks = new JsonArray();
        JsonArray dataTypes = new JsonArray();

        int fnSkipped = 0;
        for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
            if (monitor.isCancelled()) break;
            try {
                JsonObject o = functionEntry(f, currentProgram);
                if (o != null) functions.add(o); else fnSkipped++;
            } catch (Exception e) {
                println("  ! function " + f.getEntryPoint() + ": " + e);
            }
        }

        // Labels the user (or an importer) created, minus the ones that sit on a function
        // entry -- those already travel with the function record above.
        SymbolTable st = currentProgram.getSymbolTable();
        for (Symbol s : st.getAllSymbols(false)) {
            if (monitor.isCancelled()) break;
            SourceType src = s.getSource();
            if (src != SourceType.USER_DEFINED && src != SourceType.IMPORTED) continue;
            if (s.getSymbolType() == SymbolType.FUNCTION) continue;
            if (!s.getAddress().isMemoryAddress()) continue;
            JsonObject o = new JsonObject();
            o.addProperty("addr", s.getAddress().toString());
            o.addProperty("name", s.getName());
            String ns = s.getParentNamespace() == null ? null : s.getParentNamespace().getName(true);
            if (ns != null && !"Global".equals(ns)) o.addProperty("namespace", ns);
            o.addProperty("source", src.toString());
            o.addProperty("primary", s.isPrimary());
            labels.add(o);
        }

        // Defined data that carries a user name or a user-defined type. Built-in types on
        // anonymous data are regenerated by the pipeline, so they are not worth carrying.
        DataIterator dit = currentProgram.getListing().getDefinedData(true);
        while (dit.hasNext()) {
            if (monitor.isCancelled()) break;
            Data d = dit.next();
            Symbol s = d.getPrimarySymbol();
            boolean named = s != null && s.getSource() == SourceType.USER_DEFINED;
            DataType dt = d.getDataType();
            boolean userType = dt != null && dt.getSourceArchive() != null
                && !(dt instanceof BuiltInDataType) && !Undefined.isUndefined(dt);
            if (!named && !userType) continue;
            JsonObject o = new JsonObject();
            o.addProperty("addr", d.getAddress().toString());
            if (named) o.addProperty("name", s.getName());
            if (dt != null) o.addProperty("type", dt.getPathName());
            o.addProperty("length", d.getLength());
            data.add(o);
        }

        // Comments anywhere -- including inside function bodies, which is where most of the
        // reasoning in a reversed program actually lives.
        Listing listing = currentProgram.getListing();
        for (CommentType ct : CommentType.values()) {
            AddressIterator ai = listing.getCommentAddressIterator(ct,
                currentProgram.getMemory(), true);
            while (ai.hasNext()) {
                if (monitor.isCancelled()) break;
                Address a = ai.next();
                String text = listing.getComment(ct, a);
                if (text == null || text.isEmpty()) continue;
                JsonObject o = new JsonObject();
                o.addProperty("addr", a.toString());
                o.addProperty("type", ct.name());
                o.addProperty("text", text);
                comments.add(o);
            }
        }

        // User bookmarks only. Error/Warning/Analysis bookmarks are pipeline output.
        Iterator<Bookmark> bmIter = currentProgram.getBookmarkManager().getBookmarksIterator();
        while (bmIter.hasNext()) {
            if (monitor.isCancelled()) break;
            Bookmark b = bmIter.next();
            String t = b.getTypeString();
            if (!BookmarkType.NOTE.equals(t) && !BookmarkType.INFO.equals(t)) continue;
            JsonObject o = new JsonObject();
            o.addProperty("addr", b.getAddress().toString());
            o.addProperty("type", t);
            o.addProperty("category", b.getCategory());
            o.addProperty("comment", b.getComment());
            bookmarks.add(o);
        }

        // Inventory only -- see the header note about .gdt archives.
        Iterator<DataType> allTypes = currentProgram.getDataTypeManager().getAllDataTypes();
        while (allTypes.hasNext()) {
            DataType dt = allTypes.next();
            if (dt instanceof BuiltInDataType) continue;
            if (!(dt instanceof Composite || dt instanceof ghidra.program.model.data.Enum
                  || dt instanceof TypeDef || dt instanceof FunctionDefinition)) continue;
            JsonObject o = new JsonObject();
            o.addProperty("path", dt.getPathName());
            o.addProperty("kind", dt.getClass().getSimpleName());
            o.addProperty("size", dt.getLength());
            dataTypes.add(o);
        }

        root.add("functions", functions);
        root.add("labels", labels);
        root.add("data", data);
        root.add("comments", comments);
        root.add("bookmarks", bookmarks);
        root.add("dataTypes", dataTypes);

        // Name the file after the PROJECT PATH: two programs can share a name in
        // different folders, and a name-only file would silently overwrite one with the other.
        String fname = currentProgram.getDomainFile().getPathname()
            .replaceAll("^/", "").replaceAll("[^A-Za-z0-9._-]", "_") + ".annotations.json";
        Path out = Paths.get(outDir, fname);
        try (Writer w = new OutputStreamWriter(Files.newOutputStream(out), StandardCharsets.UTF_8)) {
            new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create().toJson(root, w);
        }

        if (writeGdt) exportGdt(currentProgram, outDir, fname);

        println("exported " + currentProgram.getName());
        println(String.format("  functions %d (skipped %d with nothing to save), labels %d, "
            + "data %d, comments %d, bookmarks %d, user data types %d",
            functions.size(), fnSkipped, labels.size(), data.size(),
            comments.size(), bookmarks.size(), dataTypes.size()));
        if (dataTypes.size() > 0)
            println("  NOTE: " + dataTypes.size() + " user data type(s) are LISTED only -- "
                + "also export a .gdt archive if you need them back.");
        println("  -> " + out.toAbsolutePath());
    }

    // Write the program's whole data-type manager to a .gdt archive. Preferred over trying
    // to serialize layouts into the JSON: this is Ghidra's own format, so it round-trips
    // exactly and can simply be opened in the Data Type Manager of the target program.
    private void exportGdt(Program program, String outDir, String jsonName) {
        String base = jsonName.endsWith(".annotations.json")
            ? jsonName.substring(0, jsonName.length() - ".annotations.json".length())
            : jsonName;
        java.io.File out = new java.io.File(outDir, base + ".gdt");
        FileDataTypeManager fdtm = null;
        int copied = 0, failed = 0;
        try {
            if (out.exists() && !out.delete())
                { println("  ! could not replace " + out); return; }
            fdtm = FileDataTypeManager.createFileArchive(out);
            int tx = fdtm.startTransaction("export");
            try {
                Iterator<DataType> it = program.getDataTypeManager().getAllDataTypes();
                while (it.hasNext()) {
                    DataType dt = it.next();
                    try {
                        fdtm.addDataType(dt, DataTypeConflictHandler.DEFAULT_HANDLER);
                        copied++;
                    } catch (Exception e) { failed++; }
                }
            } finally {
                fdtm.endTransaction(tx, true);
            }
            fdtm.save();
            println("  .gdt: " + copied + " type(s)" + (failed > 0 ? ", " + failed + " failed" : "")
                + " -> " + out.getAbsolutePath());
        } catch (Exception e) {
            println("  ! .gdt export failed: " + e);
        } finally {
            if (fdtm != null) try { fdtm.close(); } catch (Exception ignored) { }
        }
    }

    private JsonObject programHeader(Program currentProgram) {
        JsonObject p = new JsonObject();
        p.addProperty("name", currentProgram.getName());
        p.addProperty("path", currentProgram.getDomainFile().getPathname());
        p.addProperty("languageId", currentProgram.getLanguageID().getIdAsString());
        p.addProperty("languageVersion", currentProgram.getLanguage().getVersion()
            + "." + currentProgram.getLanguage().getMinorVersion());
        p.addProperty("compilerSpec", currentProgram.getCompilerSpec().getCompilerSpecID().getIdAsString());
        p.addProperty("imageBase", currentProgram.getImageBase().toString());
        p.addProperty("addressableUnitSize",
            currentProgram.getAddressFactory().getDefaultAddressSpace().getAddressableUnitSize());
        p.addProperty("executablePath", currentProgram.getExecutablePath());
        return p;
    }

    // Returns null when the function carries nothing a human authored.
    private JsonObject functionEntry(Function f, Program currentProgram) {
        Symbol s = f.getSymbol();
        boolean named = s != null && s.getSource() != SourceType.DEFAULT;
        String plate = f.getComment();
        String repeat = f.getRepeatableComment();
        String[] tags = f.getTags().stream().map(t -> t.getName()).toArray(String[]::new);

        JsonArray vars = new JsonArray();
        for (Variable v : f.getAllVariables()) {
            SourceType vs = v.getSource();
            if (vs == SourceType.DEFAULT) continue;
            JsonObject o = new JsonObject();
            o.addProperty("name", v.getName());
            o.addProperty("type", v.getDataType() == null ? null : v.getDataType().getPathName());
            o.addProperty("storage", v.getVariableStorage().toString());
            o.addProperty("isParam", v instanceof Parameter);
            if (v instanceof Parameter) o.addProperty("ordinal", ((Parameter) v).getOrdinal());
            o.addProperty("comment", v.getComment());
            vars.add(o);
        }

        boolean sigCommitted = f.getSignatureSource() != SourceType.DEFAULT;
        if (!named && plate == null && repeat == null && tags.length == 0
            && vars.size() == 0 && !sigCommitted && !f.hasNoReturn()) return null;

        JsonObject o = new JsonObject();
        o.addProperty("entry", f.getEntryPoint().toString());
        o.addProperty("name", f.getName());
        o.addProperty("source", s == null ? "DEFAULT" : s.getSource().toString());
        o.addProperty("prototype", f.getPrototypeString(true, false));
        o.addProperty("signatureSource", f.getSignatureSource().toString());
        o.addProperty("callingConvention", f.getCallingConventionName());
        o.addProperty("noReturn", f.hasNoReturn());
        o.addProperty("bodySizeUnits", f.getBody().getNumAddresses());
        if (plate != null) o.addProperty("plate", plate);
        if (repeat != null) o.addProperty("repeatable", repeat);
        if (tags.length > 0) {
            JsonArray ta = new JsonArray();
            for (String t : tags) ta.add(t);
            o.add("tags", ta);
        }
        if (vars.size() > 0) o.add("vars", vars);
        return o;
    }
}
